server:
  port: 8085
  servlet:
    context-path: /
  shutdown: "graceful"

spring:
  data:
    mongodb:
      username: admin
      database: springboot-mongo
      password: password
      port: '27017'
      host: localhost
#      uri: mongodb+srv://mongo_user:mongo_pass@host-demo.mongodb.net/database_sys?retryWrites=true&w=majority
#  liquibase:
#    change-log: classpath:db.changelog/db.changelog-root.xml
#    url: mongodb+srv://admin:password@localhost/springboot-mongo?authSource=admin


azure-storage:
  connectionString: "DefaultEndpointsProtocol=https;AccountName=pushstore;AccountKey=2FQuxjl16w566WIaQlCqOkOu6LrPee+Bgv1hXUZOxwQkfMm+rxlTe7USlk2Bgvub9H17bGjl7h2Z+AStLS1m3Q==;EndpointSuffix=core.windows.net"
  container: pulseops
  sasToken: ${AZURE_STORAGE_SASTOKEN}
  account: ${AZURE_STORAGE_USERNAME}
  accountKey: ${AZURE_STORAGE_PASSWORD}

transaction:
  url:

