server:
  port: 8085
  servlet:
    context-path: /
  shutdown: "graceful"

spring:
  data:
    mongodb:
#      authentication-database: admin
#      username: admin
#      password: password
      database: springboot-mongo
      port: '27017'
      host: localhost
#      uri: mongodb+srv://mongo_user:mongo_pass@host-demo.mongodb.net/database_sys?retryWrites=true&w=majority
#  liquibase:
#    change-log: classpath:db.changelog/db.changelog-root.xml
#    url: mongodb+srv://admin:password@localhost/springboot-mongo?authSource=admin

azure-storage:
  connectionString: "DefaultEndpointsProtocol=https;AccountName=pushstore;AccountKey=2FQuxjl16w566WIaQlCqOkOu6LrPee+Bgv1hXUZOxwQkfMm+rxlTe7USlk2Bgvub9H17bGjl7h2Z+AStLS1m3Q==;EndpointSuffix=core.windows.net"
  container: pulseops
  sasToken: sig=caS11wQ%2FGuGdzjY%2BzEVFtPaRm5nTT8ZO8okQKql9vDw%3D&st=2022-12-17T08%3A24%3A02Z&se=2022-12-19T15%3A24%3A02Z&sv=2019-02-02&sp=raw&sr=c
  account: pushstore
  accountKey: 2FQuxjl16w566WIaQlCqOkOu6LrPee+Bgv1hXUZOxwQkfMm+rxlTe7USlk2Bgvub9H17bGjl7h2Z+AStLS1m3Q==
  storage-account-url: https://pushstore.blob.core.windows.net/pulseops

#  ${API_URL}/azurestorage/${VERSION_CONTEXT_PATH}/?container=${azure-storage.container}&blob={{blobName}}

# https://pushstore.blob.core.windows.net/
# https://pushstore-secondary.blob.core.windows.net/

#/subscriptions/59cb6c37-f81e-4b27-822e-5c2cbd7fbf3f/resourceGroups/tech/providers/Microsoft.Storage/storageAccounts/pushstore
#/subscriptions/59cb6c37-f81e-4b27-822e-5c2cbd7fbf3f/resourceGroups/tech/providers/Microsoft.Storage/storageAccounts/pushstore/blobServices/default


transaction:
  url:

